/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.movieController;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Acer
 */

public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    movieController dmc;
    public mainView() {
        initComponents();
        dmc = new movieController(this);
        dmc.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataMovie = new javax.swing.JTable();
        jLJudul = new javax.swing.JLabel();
        jTFJudul = new javax.swing.JTextField();
        jLPenokohan = new javax.swing.JLabel();
        jTFPenokohan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFAlur = new javax.swing.JTextField();
        jLAkting = new javax.swing.JLabel();
        jTFAkting = new javax.swing.JTextField();
        jBTambah = new javax.swing.JButton();
        jBUpdate = new javax.swing.JButton();
        jTFId = new javax.swing.JTextField();
        jTFId2 = new javax.swing.JTextField();
        jBDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelDataMovie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul", "Alur", "Penokohan", "Akting", "Rating"
            }
        ));
        tabelDataMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMovieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataMovie);

        jLJudul.setText("Judul");

        jTFJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFJudulActionPerformed(evt);
            }
        });

        jLPenokohan.setText("Penokohan");

        jLabel1.setText("Alur");

        jLAkting.setText("Akting");

        jBTambah.setText("Tambah");
        jBTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTambahActionPerformed(evt);
            }
        });

        jBUpdate.setText("Update");
        jBUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBUpdateMouseClicked(evt);
            }
        });
        jBUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateActionPerformed(evt);
            }
        });

        jTFId.setEditable(false);
        jTFId.setUI(null);
        jTFId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIdActionPerformed(evt);
            }
        });

        jTFId2.setEditable(false);
        jTFId2.setText("id");
        jTFId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFId2ActionPerformed(evt);
            }
        });

        jBDelete.setText("Delete");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLJudul)
                    .addComponent(jTFJudul)
                    .addComponent(jLPenokohan)
                    .addComponent(jLabel1)
                    .addComponent(jTFAlur)
                    .addComponent(jTFPenokohan)
                    .addComponent(jLAkting)
                    .addComponent(jTFAkting)
                    .addComponent(jBTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jBUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFAlur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPenokohan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPenokohan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAkting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFAkting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDelete)
                .addGap(45, 45, 45)
                .addComponent(jTFId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFJudulActionPerformed

    private void jBTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTambahActionPerformed
        // TODO add your handling code here:
        dmc.insert();
        dmc.isiTable();
    }//GEN-LAST:event_jBTambahActionPerformed

    private void jBUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateActionPerformed
        // TODO add your handling code here:
        dmc.update();
        dmc.isiTable();
    }//GEN-LAST:event_jBUpdateActionPerformed

    private void jTFIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdActionPerformed

    private void jBUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBUpdateMouseClicked
        
    }//GEN-LAST:event_jBUpdateMouseClicked

    private void jTFId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFId2ActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        // TODO add your handling code here:
        dmc.delete();
        dmc.isiTable();
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void tabelDataMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMovieMouseClicked
        // TODO add your handling code here:
        int baris = tabelDataMovie.getSelectedRow();
        jTFId2.setText(tabelDataMovie.getValueAt(baris, 0).toString());
        jTFJudul.setText(tabelDataMovie.getValueAt(baris, 1).toString());
        jTFAlur.setText(tabelDataMovie.getValueAt(baris, 2).toString());
        jTFPenokohan.setText(tabelDataMovie.getValueAt(baris, 3).toString());
        jTFAkting.setText(tabelDataMovie.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_tabelDataMovieMouseClicked

    public JTextField getjTFId2() {
        return jTFId2;
    }

    public void setjTFId2(JTextField jTFId2) {
        this.jTFId2 = jTFId2;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBTambah;
    private javax.swing.JButton jBUpdate;
    private javax.swing.JLabel jLAkting;
    private javax.swing.JLabel jLJudul;
    private javax.swing.JLabel jLPenokohan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAkting;
    private javax.swing.JTextField jTFAlur;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFId2;
    private javax.swing.JTextField jTFJudul;
    private javax.swing.JTextField jTFPenokohan;
    private javax.swing.JTable tabelDataMovie;
    // End of variables declaration//GEN-END:variables

    public JTable getTabelDataMovie() {
        return tabelDataMovie;
    }

    public void setTabelDataMovie(JTable tabelDataMovie) {
        this.tabelDataMovie = tabelDataMovie;
    }

    public JTextField getjTFAkting() {
        return jTFAkting;
    }

    public void setjTFAkting(JTextField jTFAkting) {
        this.jTFAkting = jTFAkting;
    }

    public JTextField getjTFAlur() {
        return jTFAlur;
    }

    public void setjTFAlur(JTextField jTFAlur) {
        this.jTFAlur = jTFAlur;
    }

    public JTextField getjTFJudul() {
        return jTFJudul;
    }

    public void setjTFJudul(JTextField jTFJudul) {
        this.jTFJudul = jTFJudul;
    }

    public JTextField getjTFPenokohan() {
        return jTFPenokohan;
    }

    public void setjTFPenokohan(JTextField jTFPenokohan) {
        this.jTFPenokohan = jTFPenokohan;
    }

    public JTextField getjTFId() {
        return jTFId;
    }

    public void setjTFId(JTextField jTFId) {
        this.jTFId = jTFId;
    }

    

}
